# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-12 16:28
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0008_auto_20170112_1628'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_time', models.DateTimeField(default=datetime.datetime(2017, 1, 12, 16, 28, 40, 220803, tzinfo=utc), verbose_name='Time Logged')),
                ('comment', models.CharField(max_length=1000)),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Meal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
