# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-03 04:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('userlog', '0003_auto_20170324_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlog',
            name='log_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 3, 4, 41, 3, 42088, tzinfo=utc), verbose_name='Time Logged'),
        ),
    ]
