# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-22 23:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('userlog', '0003_auto_20170217_0258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlog',
            name='log_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 22, 23, 11, 51, 474117, tzinfo=utc), verbose_name='Time Logged'),
        ),
    ]
