# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-11 14:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('userlog', '0004_auto_20170403_0441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlog',
            name='log_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 11, 14, 4, 51, 928163, tzinfo=utc), verbose_name='Time Logged'),
        ),
    ]
