# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-30 00:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userlog', '0023_auto_20170527_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlog',
            name='log_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Time Logged'),
        ),
    ]
