# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-27 09:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_edit_date', models.DateTimeField(verbose_name='Last Date Edited')),
                ('title', models.CharField(default='Title', max_length=100)),
                ('entry', models.CharField(max_length=1000)),
                ('rating', models.IntegerField(default=0)),
            ],
        ),
    ]
