# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-30 01:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import home.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Logger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_edit_date', models.DateTimeField(verbose_name='Last Date Edited')),
                ('title', models.CharField(default='Title', max_length=100)),
                ('entry', models.CharField(max_length=1000)),
                ('rating', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date of Birth')),
                ('sex_type', models.IntegerField(default=home.models.Sex(0))),
                ('user_type', models.IntegerField(default=home.models.User_Type(0))),
                ('check_comment', models.CharField(max_length=100)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
