# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-10 01:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_logger_testnum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logger',
            name='testNum',
        ),
    ]
