# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-10 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20161210_0159'),
    ]

    operations = [
        migrations.AddField(
            model_name='logger',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='meal',
            name='calories',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='meal_type',
            name='description',
            field=models.CharField(default='Title', max_length=50),
        ),
    ]
