# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-10 13:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20161210_1357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal_type',
            name='rating',
        ),
    ]
