# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-12 16:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_userlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlog',
            name='meal',
        ),
        migrations.RemoveField(
            model_name='userlog',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserLog',
        ),
    ]
