# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-22 23:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20170112_1628'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(default='Title', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='meal',
            name='restaurant_offering',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.Restaurant'),
        ),
    ]
