# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-24 22:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=100)),
                ('calories', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Meal_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type_name', models.CharField(max_length=100)),
                ('description', models.CharField(default='Title', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(default='Title', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='meal',
            name='food_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meal.Meal_Type'),
        ),
        migrations.AddField(
            model_name='meal',
            name='restaurant_offering',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='meal.Restaurant'),
        ),
    ]
