# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-24 22:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='meal',
            name='food_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='meal.Meal_Type'),
        ),
    ]
